#!/bin/bash

source ./common.sh

rm -rf $SERVER_PATH $BACKUP_PATH $CA_PATH

mkdir -p $SERVER_PATH
mkdir -p $BACKUP_PATH
mkdir -p $CA_PATH

genkeypair $SERVER_KEYSTORE $SERVER_ALIAS
genkeypair $BACKUP_KEYSTORE $BACKUP_ALIAS

genca server-ca $SERVER_CA
genca client-ca $CLIENT_CA

signcert $SERVER_KEYSTORE $SERVER_ALIAS $SERVER_CA $SERVER_CA_ALIAS
signcert $BACKUP_KEYSTORE $BACKUP_ALIAS $SERVER_CA $SERVER_CA_ALIAS

trust $SERVER_TRUSTSTORE_FOR_CLIENT $CLIENT_CA $CLIENT_CA_ALIAS
trust $SERVER_TRUSTSTORE_FOR_BACKUP $SERVER_CA $SERVER_CA_ALIAS

trust $BACKUP_TRUSTSTORE $SERVER_CA $SERVER_CA_ALIAS
